/** linux/input-event-codes.h key names → evdev key codes. */

export const EVDEV_KEYS: Record<string, number> = {
  KEY_ESC: 1,
  KEY_1: 2,
  KEY_2: 3,
  KEY_3: 4,
  KEY_4: 5,
  KEY_5: 6,
  KEY_6: 7,
  KEY_7: 8,
  KEY_8: 9,
  KEY_9: 10,
  KEY_0: 11,
  KEY_MINUS: 12,
  KEY_EQUAL: 13,
  KEY_BACKSPACE: 14,
  KEY_TAB: 15,
  KEY_Q: 16,
  KEY_W: 17,
  KEY_E: 18,
  KEY_R: 19,
  KEY_T: 20,
  KEY_Y: 21,
  KEY_U: 22,
  KEY_I: 23,
  KEY_O: 24,
  KEY_P: 25,
  KEY_LEFTBRACE: 26,
  KEY_RIGHTBRACE: 27,
  KEY_ENTER: 28,
  KEY_LEFTCTRL: 29,
  KEY_A: 30,
  KEY_S: 31,
  KEY_D: 32,
  KEY_F: 33,
  KEY_G: 34,
  KEY_H: 35,
  KEY_J: 36,
  KEY_K: 37,
  KEY_L: 38,
  KEY_SEMICOLON: 39,
  KEY_APOSTROPHE: 40,
  KEY_GRAVE: 41,
  KEY_LEFTSHIFT: 42,
  KEY_BACKSLASH: 43,
  KEY_Z: 44,
  KEY_X: 45,
  KEY_C: 46,
  KEY_V: 47,
  KEY_B: 48,
  KEY_N: 49,
  KEY_M: 50,
  KEY_COMMA: 51,
  KEY_DOT: 52,
  KEY_SLASH: 53,
  KEY_RIGHTSHIFT: 54,
  KEY_LEFTALT: 56,
  KEY_RIGHTALT: 100,
  KEY_RIGHTCTRL: 97,
  KEY_SPACE: 57,
  KEY_CAPSLOCK: 58,
  KEY_F1: 59,
  KEY_F2: 60,
  KEY_F3: 61,
  KEY_F4: 62,
  KEY_F5: 63,
  KEY_F6: 64,
  KEY_F7: 65,
  KEY_F8: 66,
  KEY_F9: 67,
  KEY_F10: 68,
  KEY_NUMLOCK: 69,
  KEY_SCROLLLOCK: 70,
  KEY_F11: 87,
  KEY_F12: 88,
  KEY_F13: 183,
  KEY_F14: 184,
  KEY_F15: 185,
  KEY_F16: 186,
  KEY_F17: 187,
  KEY_F18: 188,
  KEY_F19: 189,
  KEY_F20: 190,
  KEY_F21: 191,
  KEY_F22: 192,
  KEY_F23: 193,
  KEY_F24: 194,
  KEY_ZENKAKUHANKAKU: 85,
  KEY_KP1: 72,
  KEY_KP2: 73,
  KEY_KP3: 74,
  KEY_KP4: 75,
  KEY_KP5: 76,
  KEY_KP6: 77,
  KEY_KP7: 78,
  KEY_KP8: 79,
  KEY_KP9: 80,
  KEY_KP0: 82,
  KEY_KPMINUS: 74,
  KEY_KPPLUS: 78,
  KEY_KPDOT: 83,
  KEY_KPSLASH: 98,
  KEY_KPASTERISK: 55,
  KEY_KPENTER: 96,
  KEY_KPEQUAL: 117,
  KEY_HOME: 102,
  KEY_UP: 103,
  KEY_PAGEUP: 104,
  KEY_LEFT: 105,
  KEY_RIGHT: 106,
  KEY_END: 107,
  KEY_DOWN: 108,
  KEY_PAGEDOWN: 109,
  KEY_INSERT: 110,
  KEY_DELETE: 111,
  KEY_MACRO: 112,
  KEY_MUTE: 113,
  KEY_VOLUMEDOWN: 114,
  KEY_VOLUMEUP: 115,
  KEY_POWER: 116,
  KEY_PAUSE: 119,
  KEY_KPCOMMA: 121,
  KEY_HANJA: 123,
  KEY_YEN: 124,
  KEY_LEFTMETA: 125,
  KEY_RIGHTMETA: 126,
  KEY_COMPOSE: 127,
  KEY_STOP: 128,
  KEY_AGAIN: 129,
  KEY_PROPS: 130,
  KEY_UNDO: 131,
  KEY_FRONT: 132,
  KEY_COPY: 133,
  KEY_OPEN: 134,
  KEY_PASTE: 135,
  KEY_FIND: 136,
  KEY_CUT: 137,
  KEY_HELP: 138,
  KEY_MENU: 139,
  KEY_PLAYPAUSE: 164,
  KEY_PREVIOUSSONG: 165,
  KEY_NEXTSONG: 171,
};

/** Whether the key is a mouse button (BTN_* codes live at >= 0x100). */
export function isMouseButton(code: number): boolean {
  return code >= 0x100 && code < 0x300;
}

const FRIENDLY_LABELS: Record<string, string> = {
  KEY_ESC: "Esc",
  KEY_MINUS: "-",
  KEY_EQUAL: "=",
  KEY_BACKSPACE: "Backspace",
  KEY_TAB: "Tab",
  KEY_LEFTBRACE: "[",
  KEY_RIGHTBRACE: "]",
  KEY_ENTER: "Enter",
  KEY_LEFTCTRL: "Left Ctrl",
  KEY_SEMICOLON: ";",
  KEY_APOSTROPHE: "'",
  KEY_GRAVE: "`",
  KEY_LEFTSHIFT: "Left Shift",
  KEY_BACKSLASH: "\\",
  KEY_COMMA: ",",
  KEY_DOT: ".",
  KEY_SLASH: "/",
  KEY_RIGHTSHIFT: "Right Shift",
  KEY_LEFTALT: "Left Alt",
  KEY_RIGHTALT: "Right Alt",
  KEY_RIGHTCTRL: "Right Ctrl",
  KEY_SPACE: "Space",
  KEY_CAPSLOCK: "Caps Lock",
  KEY_NUMLOCK: "Num Lock",
  KEY_SCROLLLOCK: "Scroll Lock",
  KEY_KPMINUS: "Keypad -",
  KEY_KPPLUS: "Keypad +",
  KEY_KPDOT: "Keypad .",
  KEY_KPSLASH: "Keypad /",
  KEY_KPASTERISK: "Keypad *",
  KEY_KPENTER: "Keypad Enter",
  KEY_KPEQUAL: "Keypad =",
  KEY_HOME: "Home",
  KEY_UP: "Up",
  KEY_PAGEUP: "Page Up",
  KEY_LEFT: "Left",
  KEY_RIGHT: "Right",
  KEY_END: "End",
  KEY_DOWN: "Down",
  KEY_PAGEDOWN: "Page Down",
  KEY_INSERT: "Insert",
  KEY_DELETE: "Delete",
  KEY_MUTE: "Mute",
  KEY_VOLUMEDOWN: "Volume Down",
  KEY_VOLUMEUP: "Volume Up",
  KEY_POWER: "Power",
  KEY_PAUSE: "Pause",
  KEY_LEFTMETA: "Left Meta",
  KEY_RIGHTMETA: "Right Meta",
  KEY_COMPOSE: "Compose",
  KEY_STOP: "Stop",
  KEY_AGAIN: "Again",
  KEY_UNDO: "Undo",
  KEY_COPY: "Copy",
  KEY_PASTE: "Paste",
  KEY_FIND: "Find",
  KEY_CUT: "Cut",
  KEY_HELP: "Help",
  KEY_MENU: "Menu",
  KEY_PLAYPAUSE: "Play/Pause",
  KEY_PREVIOUSSONG: "Previous Track",
  KEY_NEXTSONG: "Next Track",
  KEY_ZENKAKUHANKAKU: "Zenkaku/Hankaku",
};

/** Friendly display name for an evdev key name, e.g. "KEY_RIGHTALT" → "Right Alt". */
export function labelForEvdevKey(name: string): string {
  if (name in FRIENDLY_LABELS) return FRIENDLY_LABELS[name];
  if (name.startsWith("KEY_F") && /^\d+$/.test(name.slice(5))) return `F${name.slice(5)}`;
  if (name.startsWith("KEY_KP") && /^\d$/.test(name.slice(6))) return `Keypad ${name.slice(6)}`;
  if (name.startsWith("KEY_") && name.length === 5) return name[4];
  if (name.startsWith("KEY_") && /^\d+$/.test(name.slice(4))) return name.slice(4);
  const spaced = name
    .replace(/^KEY_/, "")
    .toLowerCase()
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
  return spaced;
}

/**
 * Key names from uiohook-napi's UiohookKey object that make sense as
 * push-to-talk hotkeys (excludes mice buttons and media keys this app does not use).
 */
export const UIOHOOK_KEY_NAMES: string[] = [
  "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
  "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
  "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
  "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12",
  "F13", "F14", "F15", "F16", "F17", "F18", "F19", "F20", "F21", "F22", "F23", "F24",
  "Ctrl", "CtrlRight", "Shift", "ShiftRight", "Alt", "AltRight", "Meta", "MetaRight",
  "Space", "Enter", "Tab", "Backspace", "CapsLock", "Escape",
  "PageUp", "PageDown", "Home", "End", "Insert", "Delete",
  "ArrowLeft", "ArrowUp", "ArrowRight", "ArrowDown",
  "Numpad0", "Numpad1", "Numpad2", "Numpad3", "Numpad4",
  "Numpad5", "Numpad6", "Numpad7", "Numpad8", "Numpad9",
  "NumpadEnter", "NumpadMultiply", "NumpadAdd", "NumpadSubtract", "NumpadDivide", "NumpadDecimal",
  "Semicolon", "Equal", "Comma", "Minus", "Period", "Slash", "Backquote",
  "BracketLeft", "Backslash", "BracketRight", "Quote", "PrintScreen",
];
